apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-cicd
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxMy
  template:
    metadata:
      labels:
        app: nginxMY
    spec:
      containers:
      - name: django-app
        image: prathameshdoni/changeHere
        ports:
        - containerPort: 80
